#+TITLE:     Emacs Club this Week
#+AUTHOR:    Emacs Club core
#+EMAIL:     emacsclub-core@lists.seas.upenn.edu
#+DATE:      2012-02-06 Mon
#+DESCRIPTION: 
#+KEYWORDS: 
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 

Thanks everyone for coming out to last week's meeting. 

The meeting this week will be at a higher level of difficulty, 
and you might get a little lost if you don't yet know how to use 
emacs or haven't gone through the tutorial yet. 

We'll have a beginner meeting again next week where we'll go over 
some more basic stuff. 

* Command of the Week
  
  ~C-c t~ brings up the tutorial. You'll always find the basic key commands
  you need to remember on this page. A more modern emacs tutorial that is much
  easier to follow and better written can be found [[http://www.cs.iupui.edu/~aharris/emchap/EmacsGuide.html][here]] and is highly 
  recommended.

* Next Session (Intermediate Level)

  The next emacsclub meeting will be on Tuesday Feb 7 at 6pm in Room ??.
  
  We'll be going through a few of the basic standard packages (plugins)
  that you can install for emacs, and a few other cool things that relate
  to the emacsclub website. If you've gone through a tutorial, you should
  be able to keep up with most of the things we cover in this session. We can
  always help you out if you get stuck!

  - The Emacs Starter Kit [[https://github.com/technomancy/emacs-starter-kit]]
	A useful group of emacs packages that is bundled in an easy to use way. Very
	handy!

  - Getting started with Elnode [[http://www.emacswiki.org/emacs/Elnode]]
	Elnode is an http server for emacs. We will host the emacsclub site with 
	elnode to demo its potential. 

  - Org Mode [[http://orgmode.org/]]
	The best organizational tool any programmer could ask for.
    
