Emacs Intro

 -- This introduction borrows heavily from Andy Harris's Emacs Guide,
 Prima Tech 2000. 

* Why choose emacs

  - Emacs is good for powerful text editing
  - Know which editor is good for the job. Emacs might not always be
    the best choice.
  - Emacs can radically change the way you do certain jobs. You do not
    yet realize how, because you have most likely adapted to certain
    inefficiencies in your current workflow. 
  - Emacs requires time, but, if you are willing, you will find that
    it profoundly improves the way you do some of your work. 


* Emacs Conventions

  - Emacs assumes you are smart. You will have to learn things.
  - Is built to run at 100% within terminal. Do not assume any GUI for
    emacs when you learn it.
      - Example of -nw vs. GUI.
  - Keyboard commands. Most have reasonable mnemonics. The benefit is
    that your hands will never have to leave the keyboard to perform
    extremely complex commands. 

** Control combinations
   
   - A combination of the CTRL key and some other key. 
   - Remember C-g
   - Multi-key sequences
       - C-x C-f example
       - All file mgmt commands start with C-x

** Meta combinations 

   - Control combos are not enough to encompass all of emacs' commands.
   - Meta on various systems: I know how mac works, figure out your OS
     meta key. 
       - ESC works as Meta on any system. You don't hold it down
         though. 
   - Meta as amplifier of CTRL. 
       - Example, C-f, M-f.
   - M-x and command names. 

** Help and Documentation
   
   - Before going online, check emacs for help. It is always better. 
   - If you don't know how to ask for help, use C-h ? or C-h C-h

     C-h c, C-h i, C-h m, C-h t

*** Apropos Help (C-h a)
    
    Similar to searching an index. Provides info on any matching
    command. 

*** Refcards

    All emacs installations come with refcards for your
    convenience. These are pdfs with a list of common commands for
    certain modes in emacs. In my Mac installation of emacs, I can
    find these refcards in 

    /Applications/Emacs.app/Contents/Resources/etc/refcards
    
    They are likely in a similar location in your installation. 

** Questions


* Editing
** Movement Commands

   C-f, C-b, C-p, C-n
   M-f, M-b
   C-v, M-v
   M-<, M->
   C-a, C-e

** Deletion and the Kill Ring
   
   C-d, Backspace, M-backspace
   C-k, M-k

** Marking regions

   C-@, C-SPACE
   C-w, M-w
   
** Yanking

   C-y, M-y

** Undoing
** Major Modes & Minor Modes

  C-h m
  C-c 

** Working with Line Numbers

  M-x goto-line (M-g g)
  
** Files, Buffers, and Windows

*** Files 
    Actual file on disk. This is only written to upon request. 

    C-x C-f, C-x C-s, C-x s, C-x C-w, C-x C-c
    
*** Buffer: 
    A copy of the file being edited in emacs. The actual file
    does not change until you ask emacs to save the buffer. You can
    save a buffer to a different file with 
    C-x C-w (Save file as)
    
    C-x b, C-x C-b, C-x k, M-x kill-some-buffers
    
*** Window 
    Where buffers are shown.
    
   - Working with multiple Windows
   - The difference between windows and frames
   
   C-x 0/1/2/3, C-x o, C-M-v (scroll-other-window)

*** Frame 
    Holds windows, only useful with GUIs.

** Questions


* Advanced Editing
** Search and Replace

   C-s, C-r 
   M-x replace-string, query-replace-string, replace-regexp,
   query-replace-regexp
   
** Spell Checking

   - Installing ispell
   - Using ispell (M-x ispell-buffer)

     flyspell-mode

** Keyboard Macros
   
   C-x (, C-x ), C-x e (call-last-kbd-macro)
   C-g!!
   - Do an example: Indent each line two spaces.
     
** Questions 


* Emacs and Unix
** Shell

   M-x shell

** Managing Files and Dirs with Dired
   
   Directory Editor

   C-x d, or C-x C-f on a directory

   Most editing commands supported, such as C-s

   Specific dired commands are a single key. 

   - Rename file: R
   - Copy file: C
   - Set permission on file: M
   - Mark files for deletion: d
   - Delete marked files: x
   - Unmark files: u

   Remember C-h m. Let's try this now and see what else we can do. 

** File backups

   Emacs automatically creates timely backups of your files. You will
   see these in the directory of the file being edited. 

   Backup Files: Previous copy of the file. Tilda (~) 

   Auto-Save files: Current copy of the file prior to saving
   explicitly. Gets updated frequently and on system errors. Hashes
   surround files. #filename#

   
